version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: people-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: people_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: people-api:1.0.0
    container_name: people-api
    build: ./backend/ContactApi/ 
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=people_db;Username=postgres;Password=postgres
    expose:
      - "8080"

  frontend:
    image: people-ui:1.0.0
    container_name: people-ui
    build: ./frontend/contact-ui
    restart: unless-stopped
    expose:
      - "80"

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
  
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      SCRIPT_NAME: /pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-server
    restart: unless-stopped
    command: -H tcp://portainer-agent:9001 --tlsskipverify
    ports:
      - "9052:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    depends_on:
      - portainer-agent

secrets:
  db-password:
    file: ./secrets/db-password.txt

volumes:
  db-data:
  pgadmin_data:
  portainer_data:
