apiVersion: v1
clusters:
- cluster:
    server: https://api.rm1.0a51.p1.openshiftapps.com:6443
  name: api-rm1-0a51-p1-openshiftapps-com:6443
contexts:
- context:
    cluster: api-rm1-0a51-p1-openshiftapps-com:6443
    namespace: krishnakanthr660-dev
    user: krishnakanthr660/api-rm1-0a51-p1-openshiftapps-com:6443
  name: krishnakanthr660-dev/api-rm1-0a51-p1-openshiftapps-com:6443/krishnakanthr660
current-context: krishnakanthr660-dev/api-rm1-0a51-p1-openshiftapps-com:6443/krishnakanthr660
kind: Config
users:
- name: krishnakanthr660/api-rm1-0a51-p1-openshiftapps-com:6443
  user:
    token: sha256~YePIvLJUUcK0piO7TShOxi-WXH6JNDLUIteQOWr6rdU
